WITH CHANNELS AS
(
    WITH VALID_SYSTEM_TABNUMS AS 
    (
        SELECT SYSTEM_TABNUM, SYSTEM_TABNUM_WITH_SUFFIX, PROV_CODE, SYSTEM_LINEUP_TYPE
        FROM 
        (SELECT DISTINCT MARQUEE_RULE.SYSTEM_TABNUM, MARQUEE_RULE.SYSTEM_TABNUM || MARQUEE_RULE.SUFFIX AS SYSTEM_TABNUM_WITH_SUFFIX, MARQUEE_RULE.SYSTEM_LINEUP_TYPE FROM MARQUEE_RULE) AS MARQUEE_RULE
            JOIN (SELECT DISTINCT  CHANNEL_LINEUP, PROV_CODE FROM MARQUEE ) AS CHANNEL_LINEUP_TO_PROVINCE
            ON MARQUEE_RULE.SYSTEM_TABNUM = CHANNEL_LINEUP_TO_PROVINCE.CHANNEL_LINEUP
        WHERE (PROV_CODE = "ON" AND SYSTEM_LINEUP_TYPE = "HD")
        OR (PROV_CODE <> "ON" AND SYSTEM_LINEUP_TYPE = "SD")
    )
    SELECT DISTINCT SERVICE_ID, SYSTEM_TABNUM_WITH_SUFFIX
    FROM CLICC_DTV_DOTCOM JOIN VALID_SYSTEM_TABNUMS
    ON CLICC_DTV_DOTCOM.SYSTEM_TABNUM  = VALID_SYSTEM_TABNUMS.SYSTEM_TABNUM_WITH_SUFFIX
)
SELECT DISTINCT CLICC_DTV_DOTCOM.*
FROM CHANNELS JOIN CLICC_DTV_DOTCOM
  ON CHANNELS.SERVICE_ID = CLICC_DTV_DOTCOM.SERVICE_ID
    AND CHANNELS.SYSTEM_TABNUM_WITH_SUFFIX = CLICC_DTV_DOTCOM.SYSTEM_TABNUM
